default_language_version:
    python: python3.10
exclude: "README.md" 

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files
            exclude: mlartifacts/
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: mixed-line-ending

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.7.0
      hooks:
          - id: isort

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            additional_dependencies: [flake8-bugbear, Flake8-pyproject]

    - repo: https://github.com/PyCQA/pylint
      rev: pylint-2.7.1
      hooks:
          - id: pylint

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.2.1
      hooks:
          - id: prettier
            types_or: [markdown, yaml, toml, json, dockerfile, shell]
            args: [--prose-wrap=always, --print-width=90, --tab-width=4]
