params:
    learning_rate: 0.95
    n_estimators: 100
    max_depth: 9

optim:
    optim_type: "Adam"

trainer:
    epochs: 3
    batch_size: 32

ml_ops:
    mlflow_server: "http://128.0.1.1:8080"

dataset:
    process: "short"
    train_size: 0.8
    target_name: 'isFraud'

artifacts:
    experiment_name: example-experiment
    checkpoint:
        use: false
        dirpath: checkpoints
        filename: "{epoch:02d}-{val_loss:.4f}"
        monitor: val_loss
        save_top_k: 3
        every_n_train_steps:
        every_n_epochs: 1

callbacks:
    model_summary:
        max_depth: 1
    swa:
        use: false
        lrs: 1e-3
